version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    env_file:
      - .env
  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    env_file:
      - .env
    environment:
      PMA_HOST: db
    ports:
      - "44400:80"
    
  aldebaran:
    depends_on:
      - db
    image: nightorn/aldebaran:latest
    restart: always
    env_file:
      - .env
    command: sh -c "/wait && node app"
    environment:
      - WAIT_HOSTS=db:3306
      - WAIT_SLEEP_INTERVAL=5

volumes:
  db-data: